#!/usr/bin/env sh

# --------------------------------------------------
# Automatically load scripting addition on startup
# --------------------------------------------------
sudo yabai --load-sa

# --------------------------------------------------
# Global Settings
# --------------------------------------------------
#
# Property                                  Value
# --------                                  -----
yabai -m config mouse_follows_focus         off
yabai -m config focus_follows_mouse         off
yabai -m config window_placement            second_child
yabai -m config window_topmost              off
yabai -m config window_opacity              on
yabai -m config window_shadow               float
yabai -m config window_border               off
yabai -m config window_border_width         2
yabai -m config active_window_border_color  0xB2EBDBB2
yabai -m config normal_window_border_color  0xB2282828
yabai -m config insert_window_border_color  0xB2EBDBB2
yabai -m config active_window_opacity       1.0
yabai -m config normal_window_opacity       0.95
yabai -m config split_ratio                 0.50
yabai -m config auto_balance                on
yabai -m config mouse_modifier              fn
yabai -m config mouse_action1               move
yabai -m config mouse_action2               resize

yabai -m config external_bar                all:0:0
yabai -m config layout                      bsp
yabai -m config top_padding                 10
yabai -m config bottom_padding              10
yabai -m config left_padding                10
yabai -m config right_padding               10
yabai -m config window_gap                  10
yabai -m config --space 6 layout            float

# Unmanaged
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="Telegram" app="^Telegram$" manage=off
yabai -m rule --add label="Spotify" app="^Spotify$" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add app="^System Preferences$"  manage=off border=off

